"use client";

/**
 * Test mode (T13, AGENTS.md §6 + §13.8): pre-test → learning session →
 * post-test, per-participant timestamps in browser storage, CSV export.
 * Questions are EXTERNAL (owner-supplied file; bundled SAMPLE labeled in
 * the UI) and are never generated by the pipeline — this component has its
 * own question view (no correctness feedback until the part ends, unlike
 * the in-app generated quizzes) and its own storage key.
 */
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { LiveLesson } from "./live-lesson";
import { EvalQuestionView } from "./eval-question";
import {
  addAnswer,
  findRecord,
  finishPart,
  upsertRecord,
  useEvalStore,
  type EvalRecord,
  type RecordedAnswer,
} from "@/lib/eval-store";
import {
  buildEvalCsv,
  exportEvalCsv,
  isSampleQuestions,
  loadSampleEvalQuestions,
  type EvalQuestion,
  type EvalQuestions,
} from "@/lib/eval";

type Phase = "intro" | "pre" | "session" | "post" | "done";

export function TestMode() {
  const questions: EvalQuestions = useMemo(() => loadSampleEvalQuestions(), []);
  const sample = isSampleQuestions(questions);
  const { store, save } = useEvalStore();

  const [phase, setPhase] = useState<Phase>("intro");
  const [name, setName] = useState("");
  const [part, setPart] = useState<"pre" | "post">("pre");
  const [idx, setIdx] = useState(0);
  const [picked, setPicked] = useState<number | null>(null);
  const wiz = useRef<{ partStartedAt: number; questionAt: number }>({ partStartedAt: 0, questionAt: 0 });

  const set = <K extends keyof typeof wiz.current>(k: K, v: number) => {
    wiz.current[k] = v;
  };

  const beginPart = (which: "pre" | "post") => {
    const now = Date.now();
    save((s) => upsertRecord(s, name, which, now));
    setPart(which);
    setIdx(0);
    setPicked(null);
    set("partStartedAt", now);
    set("questionAt", now);
    setPhase(which);
  };

  const total = part === "pre" ? questions.pre.length : questions.post.length;
  const current: EvalQuestion | null =
    phase === "pre" ? (questions.pre[idx] ?? null) : phase === "post" ? (questions.post[idx] ?? null) : null;

  const nextQuestion = () => {
    if (!current || picked === null) return;
    const now = Date.now();
    const answer: RecordedAnswer = {
      questionId: current.id,
      correct: picked === current.answer,
      elapsedSec: Math.max(0, Math.round((now - wiz.current.questionAt) / 1000)),
    };
    save((s) => addAnswer(s, name, part, answer, now));
    setPicked(null);
    set("questionAt", now);
    if (idx + 1 < total) {
      setIdx(idx + 1);
      return;
    }
    save((s) => finishPart(s, name, part, now));
    if (part === "pre") {
      setPhase("session");
    } else {
      setPhase("done");
    }
  };

  const record: EvalRecord | null = useMemo(
    () => (name ? findRecord(store, name) : null),
    [store, name],
  );

  return (
    <div className="mx-auto flex w-full max-w-2xl flex-col gap-6 px-6 py-10" data-testid="test-mode">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-semibold tracking-tight text-zinc-900">Learning test session</h1>
        <Link href="/" className="text-[13px] text-violet-700 hover:underline">
          ← Back to EduVoid
        </Link>
      </div>

      {sample && (
        <div
          className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 text-[12px] text-amber-800"
          data-testid="sample-banner"
        >
          Sample questions (built-in placeholder) — the owner supplies the real external exam
          file (see BLOCKERS.md). The flow and export work identically.
        </div>
      )}

      {phase === "intro" && (
        <div className="flex flex-col gap-4 rounded-xl border border-border-subtle bg-white p-5">
          <p className="text-[13px] text-zinc-600">
            {questions.title} — pre-test → learning session → post-test. Answers and timestamps
            stay in this browser and can be exported as CSV (no accounts, §2).
          </p>
          <input
            value={name}
            onChange={(e) => setName(e.target.value.toUpperCase().trim())}
            placeholder="Participant code, e.g. P1"
            data-testid="test-name-input"
            aria-label="Participant code"
            className="h-10 rounded-lg border border-border-subtle px-3 text-[14px] outline-none placeholder:text-zinc-400 focus:border-violet-400"
          />
          <div className="flex gap-2">
            <button
              type="button"
              disabled={!name}
              data-testid="test-begin"
              onClick={() => beginPart("pre")}
              className="h-10 rounded-lg bg-violet-600 px-4 text-[13px] font-medium text-white hover:bg-violet-700 disabled:opacity-40"
            >
              Begin pre-test
            </button>
            {record && record.pre.finishedAt !== null && (
              <button
                type="button"
                data-testid="test-start-post-direct"
                onClick={() => beginPart("post")}
                className="h-10 rounded-lg border border-violet-300 px-4 text-[13px] font-medium text-violet-700 hover:bg-violet-50"
              >
                Resume: post-test
              </button>
            )}
          </div>
        </div>
      )}

      {(phase === "pre" || phase === "post") && current && (
        <div className="flex flex-col gap-4 rounded-xl border border-border-subtle bg-white p-5">
          <p className="text-[12px] font-medium uppercase tracking-wide text-zinc-400">
            {part}-test · question {idx + 1} of {total}
          </p>
          <EvalQuestionView q={current} picked={picked} onPick={setPicked} />
          <button
            type="button"
            disabled={picked === null}
            data-testid="test-next"
            onClick={nextQuestion}
            className="h-10 self-start rounded-lg bg-violet-600 px-4 text-[13px] font-medium text-white hover:bg-violet-700 disabled:opacity-40"
          >
            {idx + 1 < total ? "Next question" : `Finish ${part}-test`}
          </button>
        </div>
      )}

      {phase === "session" && (
        <div className="flex flex-col gap-4">
          <div className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-2.5 text-[13px] text-violet-800" data-testid="session-prompt">
            Pre-test done for {name}. Use the learning session below, then come back and take the
            post-test. Progress saves automatically.
          </div>
          <button
            type="button"
            data-testid="test-finish-session"
            onClick={() => beginPart("post")}
            className="h-10 self-start rounded-lg bg-violet-600 px-4 text-[13px] font-medium text-white hover:bg-violet-700"
          >
            Start post-test
          </button>
          <div className="rounded-xl border border-border-subtle bg-white p-4">
            <LiveLesson topic="quantum superposition" onFail={() => undefined} />
          </div>
        </div>
      )}

      {phase === "done" && (
        <div className="flex flex-col gap-4 rounded-xl border border-border-subtle bg-white p-5" data-testid="test-done">
          <p className="text-[14px] text-zinc-700">
            Post-test finished for {name}. Both parts are saved in this browser.
          </p>
          <button
            type="button"
            data-testid="test-new-participant"
            onClick={() => {
              setName("");
              setPhase("intro");
            }}
            className="h-10 self-start rounded-lg bg-violet-600 px-4 text-[13px] font-medium text-white hover:bg-violet-700"
          >
            Next participant
          </button>
        </div>
      )}

      <div className="flex flex-col gap-2 rounded-xl border border-border-subtle bg-white p-5" data-testid="test-records">
        <div className="flex items-center justify-between">
          <p className="text-[13px] font-medium text-zinc-900">Saved participants</p>
          <button
            type="button"
            data-testid="test-export-csv"
            disabled={store.length === 0}
            onClick={() => exportEvalCsv(buildEvalCsv(store, Date.now()))}
            className="rounded-lg border border-violet-300 px-3 py-1.5 text-[12px] font-medium text-violet-700 hover:bg-violet-50 disabled:opacity-40"
          >
            Export CSV
          </button>
        </div>
        {store.length === 0 ? (
          <p className="text-[12px] text-zinc-400">No sessions yet.</p>
        ) : (
          <ul className="flex flex-col gap-1 text-[12px] text-zinc-600">
            {store.map((r) => (
              <li key={r.name} data-testid="test-record-row">
                {r.name}: pre {r.pre.answers.filter((a) => a.correct).length}/{r.pre.answers.length},
                post {r.post.answers.filter((a) => a.correct).length}/{r.post.answers.length}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
